CREATE TABLE IF NOT EXISTS quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    available INTEGER NOT NULL,
    consumed INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(api_key_id, service_id)
);

CREATE INDEX idx_quotas_api_key_id ON quotas(api_key_id);
CREATE INDEX idx_quotas_service_id ON quotas(service_id);

CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL DEFAULT 1, -- Aggregated count for the minute
    bucket_timestamp TIMESTAMPTZ NOT NULL, -- Truncated to minute boundary
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Updated indexes for minute aggregation
CREATE INDEX idx_usage_log_api_key_id ON metrics(api_key_id);
CREATE INDEX idx_usage_log_service_id ON metrics(service_id);
CREATE INDEX idx_usage_log_bucket_timestamp ON metrics(bucket_timestamp);
CREATE UNIQUE INDEX idx_usage_log_unique_minute ON metrics(api_key_id, service_id, bucket_timestamp);
