CREATE TABLE api_key_status_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    status TEXT NOT NULL REFERENCES api_key_statuses(name),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_status_events_api_key_id ON api_key_status_events(api_key_id);
CREATE INDEX idx_status_events_api_key_created ON api_key_status_events(api_key_id, created_at DESC);
