CREATE TABLE api_key_service_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    consumption_amount INTEGER NOT NULL DEFAULT 1,
    remaining_quota_after INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_usage_log_api_key_id ON api_key_service_usage_logs(api_key_id);
CREATE INDEX idx_usage_log_service_id ON api_key_service_usage_logs(service_id);
CREATE INDEX idx_usage_log_created_at ON api_key_service_usage_logs(created_at);
CREATE INDEX idx_usage_log_api_key_created ON api_key_service_usage_logs(api_key_id, created_at);
