CREATE TABLE metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL DEFAULT 1, -- Aggregated count for the minute
    bucket_timestamp TIMESTAMPTZ NOT NULL, -- Truncated to minute boundary
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Updated indexes for minute aggregation
CREATE INDEX idx_usage_log_api_key_id ON metrics(api_key_id);
CREATE INDEX idx_usage_log_service_id ON metrics(service_id);
CREATE INDEX idx_usage_log_bucket_timestamp ON metrics(bucket_timestamp);
CREATE UNIQUE INDEX idx_usage_log_unique_minute ON metrics(api_key_id, service_id, bucket_timestamp);

-- New queries for aggregation
-- name: UpsertMinuteUsage :one
INSERT INTO metrics (api_key_id, service_id, amount, bucket_timestamp)
VALUES ($1, $2, $3, $4)
ON CONFLICT (api_key_id, service_id, bucket_timestamp) 
DO UPDATE SET amount = metrics.amount + $3
RETURNING amount;

-- Batch insert usage logs for multiple events
-- name: BatchInsertUsageLogs :copyfrom
INSERT INTO metrics (api_key_id, service_id, amount, bucket_timestamp, created_at)
VALUES ($1, $2, $3, $4, $5);