// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metrics.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertUsageLogsParams struct {
	ApiKeyID        int64
	ServiceID       int64
	Amount          int32
	BucketTimestamp pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

const upsertMinuteUsage = `-- name: UpsertMinuteUsage :one
INSERT INTO metrics (api_key_id, service_id, amount, bucket_timestamp)
VALUES ($1, $2, $3, $4)
ON CONFLICT (api_key_id, service_id, bucket_timestamp) 
DO UPDATE SET amount = metrics.amount + $3
RETURNING amount
`

type UpsertMinuteUsageParams struct {
	ApiKeyID        int64
	ServiceID       int64
	Amount          int32
	BucketTimestamp pgtype.Timestamptz
}

// New queries for aggregation
func (q *Queries) UpsertMinuteUsage(ctx context.Context, arg *UpsertMinuteUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertMinuteUsage,
		arg.ApiKeyID,
		arg.ServiceID,
		arg.Amount,
		arg.BucketTimestamp,
	)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}
