// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKeyStatuses struct {
	Name        string
	Description pgtype.Text
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}

type ApiKeys struct {
	ID        int64
	UserID    int64
	KeyString string
	Status    string
	HasQuota  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Metrics struct {
	ID              int64
	ApiKeyID        int64
	ServiceID       int64
	Amount          int32
	BucketTimestamp pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Quotas struct {
	ID        int64
	ApiKeyID  int64
	ServiceID int64
	Available int32
	Consumed  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Services struct {
	ID           int64
	Name         string
	DefaultQuota int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Users struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
}
