// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKeyServiceQuotas struct {
	ID             int64
	ApiKeyID       int64
	ServiceID      int64
	InitialQuota   int32
	RemainingQuota int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ApiKeyServiceUsageLogs struct {
	ID                int64
	ApiKeyID          int64
	ServiceID         int64
	ConsumptionAmount int32
	MinuteTimestamp   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type ApiKeyStatusEvents struct {
	ID        int64
	ApiKeyID  int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ApiKeyStatuses struct {
	Name        string
	Description pgtype.Text
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}

type ApiKeys struct {
	ID        int64
	UserID    int64
	KeyString string
	Status    string
	HasQuota  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Services struct {
	ID           int64
	Name         string
	DefaultQuota int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Users struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
}
