CREATE TABLE quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    available INTEGER NOT NULL,
    consumed INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(api_key_id, service_id)
);

CREATE INDEX idx_quotas_api_key_id ON quotas(api_key_id);
CREATE INDEX idx_quotas_service_id ON quotas(service_id);

-- API Key Service Quota-related queries

-- Initialize API key service quotas with full quota
-- name: InitializeKeyServiceQuota :one
INSERT INTO quotas (api_key_id, service_id, available)
VALUES ($1, $2, $3)
ON CONFLICT (api_key_id, service_id) DO UPDATE SET
    available = $3,
    updated_at = NOW()
RETURNING *;


-- Get API key quotas with service info
-- name: GetAPIKeyQuotas :many
SELECT aksq.*, s.name as service_name
FROM quotas aksq
JOIN services s ON aksq.service_id = s.id
WHERE aksq.api_key_id = $1;

-- Get quota (consumed and available) for ($api_key_id, $service_id)
-- name: GetQuotaByID :one
SELECT aksq.consumed, aksq.available
FROM quotas aksq
WHERE aksq.api_key_id = $1 and aksq.service_id = $2;

-- Get quota (consumed and available) for an ($api_key, $service_name)
-- name: GetQuotaByName :one
SELECT aksq.consumed, aksq.available
FROM quotas aksq
JOIN services s ON aksq.service_id = s.id
JOIN api_keys ak ON aksq.api_key_id = ak.id
WHERE ak.key_string = $1 and s.name = $2;

-- Get all quotas
-- name: GetAllQuotas :many
with key_info as (
    SELECT id, has_quota FROM api_keys
    WHERE status = 'assigned'
), quota_join_key as (
    SELECT 
    q.id,q.api_key_id, q.service_id, q.available, q.consumed, ki.has_quota as has_quota
    FROM quotas q
    JOIN key_info ki ON q.api_key_id = ki.id
)
SELECT id, api_key_id, service_id, available, consumed, has_quota FROM quota_join_key
ORDER BY id
LIMIT sqlc.arg('limit')::int
OFFSET sqlc.arg('offset')::int
;

-- Reserve $amount quota for ($api_key, $service_name)
-- name: ReserveQuota :one
WITH quota_check AS (
    SELECT aksq.id, aksq.available, aksq.api_key_id, aksq.service_id
    FROM quotas aksq
    JOIN services s ON aksq.service_id = s.id
    JOIN api_keys ak ON aksq.api_key_id = ak.id
    WHERE ak.key_string = $1 AND s.name = $2 AND ak.status = 'assigned'
)
UPDATE quotas
SET available = quotas.available - $3,
    consumed = quotas.consumed + $3,
    updated_at = NOW()
FROM quota_check qc
WHERE quotas.id = qc.id
    AND qc.available >= $3
RETURNING quotas.available, quotas.consumed;

-- Refund $amount quota for ($api_key, $service_name)
-- name: RefundQuota :one
WITH quota_update AS (
    SELECT aksq.id, aksq.available, aksq.consumed
    FROM quotas aksq
    JOIN services s ON aksq.service_id = s.id
    JOIN api_keys ak ON aksq.api_key_id = ak.id
    WHERE ak.key_string = $1 AND s.name = $2 AND ak.status = 'assigned'
)
UPDATE quotas
SET available = quotas.available + $3,
    consumed = GREATEST(quotas.consumed - $3, 0),
    updated_at = NOW()
FROM quota_update qu
WHERE quotas.id = qu.id
RETURNING quotas.available, quotas.consumed;
