// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quotas.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyQuotas = `-- name: GetAPIKeyQuotas :many
SELECT aksq.id, aksq.api_key_id, aksq.service_id, aksq.available, aksq.consumed, aksq.created_at, aksq.updated_at, s.name as service_name
FROM quotas aksq
JOIN services s ON aksq.service_id = s.id
WHERE aksq.api_key_id = $1
`

type GetAPIKeyQuotasRow struct {
	ID          int64
	ApiKeyID    int64
	ServiceID   int64
	Available   int32
	Consumed    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ServiceName string
}

// Get API key quotas with service info
func (q *Queries) GetAPIKeyQuotas(ctx context.Context, apiKeyID int64) ([]*GetAPIKeyQuotasRow, error) {
	rows, err := q.db.Query(ctx, getAPIKeyQuotas, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAPIKeyQuotasRow
	for rows.Next() {
		var i GetAPIKeyQuotasRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ServiceID,
			&i.Available,
			&i.Consumed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuotaByID = `-- name: GetQuotaByID :one
SELECT aksq.consumed, aksq.available
FROM quotas aksq
WHERE aksq.api_key_id = $1 and aksq.service_id = $2
`

type GetQuotaByIDParams struct {
	ApiKeyID  int64
	ServiceID int64
}

type GetQuotaByIDRow struct {
	Consumed  int32
	Available int32
}

// Get quota (consumed and available) for ($api_key_id, $service_id)
func (q *Queries) GetQuotaByID(ctx context.Context, arg *GetQuotaByIDParams) (*GetQuotaByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuotaByID, arg.ApiKeyID, arg.ServiceID)
	var i GetQuotaByIDRow
	err := row.Scan(&i.Consumed, &i.Available)
	return &i, err
}

const getQuotaByName = `-- name: GetQuotaByName :one
SELECT aksq.consumed, aksq.available
FROM quotas aksq
JOIN services s ON aksq.service_id = s.id
JOIN api_keys ak ON aksq.api_key_id = ak.id
WHERE ak.key_string = $1 and s.name = $2
`

type GetQuotaByNameParams struct {
	KeyString string
	Name      string
}

type GetQuotaByNameRow struct {
	Consumed  int32
	Available int32
}

// Get quota (consumed and available) for an ($api_key, $service_name)
func (q *Queries) GetQuotaByName(ctx context.Context, arg *GetQuotaByNameParams) (*GetQuotaByNameRow, error) {
	row := q.db.QueryRow(ctx, getQuotaByName, arg.KeyString, arg.Name)
	var i GetQuotaByNameRow
	err := row.Scan(&i.Consumed, &i.Available)
	return &i, err
}

const initializeKeyServiceQuota = `-- name: InitializeKeyServiceQuota :one

INSERT INTO quotas (api_key_id, service_id, available)
VALUES ($1, $2, $3)
ON CONFLICT (api_key_id, service_id) DO UPDATE SET
    available = $3,
    updated_at = NOW()
RETURNING id, api_key_id, service_id, available, consumed, created_at, updated_at
`

type InitializeKeyServiceQuotaParams struct {
	ApiKeyID  int64
	ServiceID int64
	Available int32
}

// API Key Service Quota-related queries
// Initialize API key service quotas with full quota
func (q *Queries) InitializeKeyServiceQuota(ctx context.Context, arg *InitializeKeyServiceQuotaParams) (*Quotas, error) {
	row := q.db.QueryRow(ctx, initializeKeyServiceQuota, arg.ApiKeyID, arg.ServiceID, arg.Available)
	var i Quotas
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.ServiceID,
		&i.Available,
		&i.Consumed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const refundQuota = `-- name: RefundQuota :one
WITH quota_update AS (
    SELECT aksq.id, aksq.available, aksq.consumed
    FROM quotas aksq
    JOIN services s ON aksq.service_id = s.id
    JOIN api_keys ak ON aksq.api_key_id = ak.id
    WHERE ak.key_string = $1 AND s.name = $2 AND ak.status = 'assigned'
)
UPDATE quotas
SET available = quotas.available + $3,
    consumed = GREATEST(quotas.consumed - $3, 0),
    updated_at = NOW()
FROM quota_update qu
WHERE quotas.id = qu.id
RETURNING quotas.available, quotas.consumed
`

type RefundQuotaParams struct {
	KeyString string
	Name      string
	Available int32
}

type RefundQuotaRow struct {
	Available int32
	Consumed  int32
}

// Refund $amount quota for ($api_key, $service_name)
func (q *Queries) RefundQuota(ctx context.Context, arg *RefundQuotaParams) (*RefundQuotaRow, error) {
	row := q.db.QueryRow(ctx, refundQuota, arg.KeyString, arg.Name, arg.Available)
	var i RefundQuotaRow
	err := row.Scan(&i.Available, &i.Consumed)
	return &i, err
}

const reserveQuota = `-- name: ReserveQuota :one
WITH quota_check AS (
    SELECT aksq.id, aksq.available, aksq.api_key_id, aksq.service_id
    FROM quotas aksq
    JOIN services s ON aksq.service_id = s.id
    JOIN api_keys ak ON aksq.api_key_id = ak.id
    WHERE ak.key_string = $1 AND s.name = $2 AND ak.status = 'assigned'
)
UPDATE quotas
SET available = quotas.available - $3,
    consumed = quotas.consumed + $3,
    updated_at = NOW()
FROM quota_check qc
WHERE quotas.id = qc.id
    AND qc.available >= $3
RETURNING quotas.available, quotas.consumed
`

type ReserveQuotaParams struct {
	KeyString string
	Name      string
	Available int32
}

type ReserveQuotaRow struct {
	Available int32
	Consumed  int32
}

// Reserve $amount quota for ($api_key, $service_name)
func (q *Queries) ReserveQuota(ctx context.Context, arg *ReserveQuotaParams) (*ReserveQuotaRow, error) {
	row := q.db.QueryRow(ctx, reserveQuota, arg.KeyString, arg.Name, arg.Available)
	var i ReserveQuotaRow
	err := row.Scan(&i.Available, &i.Consumed)
	return &i, err
}
