CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    default_quota INTEGER NOT NULL DEFAULT 1000,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_services_name ON services(name);

-- Service-related queries

-- Create service
-- name: CreateService :one
INSERT INTO services (name, default_quota)
VALUES ($1, $2)
RETURNING id, name, default_quota;

-- Get all services
-- name: GetAllServices :many
SELECT id, name, default_quota FROM services;

-- Get service by name
-- name: GetServiceByName :one
SELECT id, name, default_quota FROM services WHERE name = $1;
