CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    default_quota INTEGER NOT NULL DEFAULT 1000,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_services_name ON services(name);

-- Service-related queries

-- Get all services
-- name: GetAllServices :many
SELECT id, name FROM services;

-- Get service by name
-- name: GetServiceByName :one
SELECT * FROM services WHERE name = $1;
