// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package dbsqlc

import (
	"context"
)

const createService = `-- name: CreateService :one

INSERT INTO services (name, default_quota)
VALUES ($1, $2)
RETURNING id, name, default_quota
`

type CreateServiceParams struct {
	Name         string
	DefaultQuota int32
}

type CreateServiceRow struct {
	ID           int64
	Name         string
	DefaultQuota int32
}

// Service-related queries
// Create service
func (q *Queries) CreateService(ctx context.Context, arg *CreateServiceParams) (*CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService, arg.Name, arg.DefaultQuota)
	var i CreateServiceRow
	err := row.Scan(&i.ID, &i.Name, &i.DefaultQuota)
	return &i, err
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, default_quota FROM services
`

type GetAllServicesRow struct {
	ID           int64
	Name         string
	DefaultQuota int32
}

// Get all services
func (q *Queries) GetAllServices(ctx context.Context) ([]*GetAllServicesRow, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllServicesRow
	for rows.Next() {
		var i GetAllServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DefaultQuota); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, name, default_quota FROM services WHERE name = $1
`

type GetServiceByNameRow struct {
	ID           int64
	Name         string
	DefaultQuota int32
}

// Get service by name
func (q *Queries) GetServiceByName(ctx context.Context, name string) (*GetServiceByNameRow, error) {
	row := q.db.QueryRow(ctx, getServiceByName, name)
	var i GetServiceByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.DefaultQuota)
	return &i, err
}
