CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users(email);

-- User-related queries

-- Create a new user with a given email
-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO NOTHING
RETURNING *;

-- Get user by email
-- name: GetUserByEmail :one
SELECT * FROM users WHERE email = $1;

-- Get all users
-- name: GetAllUsers :many
SELECT * FROM users ORDER BY created_at DESC;
